# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

local_bic_gaussian_cpp <- function(j, parents, X) {
    .Call(`_M2BayesNet_local_bic_gaussian_cpp`, j, parents, X)
}

bic_score_gaussian_cpp <- function(adj, X) {
    .Call(`_M2BayesNet_bic_score_gaussian_cpp`, adj, X)
}

bic_score_multinom_cpp <- function(adj, X_disc, n_levels) {
    .Call(`_M2BayesNet_bic_score_multinom_cpp`, adj, X_disc, n_levels)
}

precompute_local_scores_gaussian <- function(X) {
    .Call(`_M2BayesNet_precompute_local_scores_gaussian`, X)
}

precompute_local_scores_multinom <- function(X_disc, n_levels) {
    .Call(`_M2BayesNet_precompute_local_scores_multinom`, X_disc, n_levels)
}

best_score_given_predecessors <- function(scores_j, preds_mask) {
    .Call(`_M2BayesNet_best_score_given_predecessors`, scores_j, preds_mask)
}

build_adj_from_parent_masks <- function(parent_masks) {
    .Call(`_M2BayesNet_build_adj_from_parent_masks`, parent_masks)
}

branch_and_bound_bn <- function(X_nullable = NULL, X_disc_nullable = NULL, n_levels_nullable = NULL, distribution = "gaussian") {
    .Call(`_M2BayesNet_branch_and_bound_bn`, X_nullable, X_disc_nullable, n_levels_nullable, distribution)
}

rcpp_hello <- function() {
    .Call(`_M2BayesNet_rcpp_hello`)
}

