# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bic_score_gaussian_cpp <- function(adj, X) {
    .Call(`_M2BayesNet_bic_score_gaussian_cpp`, adj, X)
}

bic_score_multinom_cpp <- function(adj, X_disc, n_levels) {
    .Call(`_M2BayesNet_bic_score_multinom_cpp`, adj, X_disc, n_levels)
}

precompute_local_scores_gaussian_cpp <- function(X) {
    .Call(`_M2BayesNet_precompute_local_scores_gaussian_cpp`, X)
}

precompute_local_scores_multinom_cpp <- function(X_disc, n_levels) {
    .Call(`_M2BayesNet_precompute_local_scores_multinom_cpp`, X_disc, n_levels)
}

best_score_given_predecessors_cpp <- function(scores_j, preds_mask) {
    .Call(`_M2BayesNet_best_score_given_predecessors_cpp`, scores_j, preds_mask)
}

build_adj_from_parent_masks <- function(parent_masks) {
    .Call(`_M2BayesNet_build_adj_from_parent_masks`, parent_masks)
}

branch_and_bound_bn_cpp <- function(X_nullable = NULL, X_disc_nullable = NULL, n_levels_nullable = NULL, distribution = "gaussian") {
    .Call(`_M2BayesNet_branch_and_bound_bn_cpp`, X_nullable, X_disc_nullable, n_levels_nullable, distribution)
}

hill_climbing_bn_cpp_internal <- function(X, X_disc, n_levels, max_iter, verbose, score_type) {
    .Call(`_M2BayesNet_hill_climbing_bn_cpp_internal`, X, X_disc, n_levels, max_iter, verbose, score_type)
}

tabu_search_bn_cpp_internal <- function(X, X_disc, n_levels, max_iter, tabu_tenure, verbose, score_type) {
    .Call(`_M2BayesNet_tabu_search_bn_cpp_internal`, X, X_disc, n_levels, max_iter, tabu_tenure, verbose, score_type)
}

rcpp_hello <- function() {
    .Call(`_M2BayesNet_rcpp_hello`)
}

